### ISSUE TITLE
ConfigMap issue on current chart version

### ISSUE THREAD

**Issue by Waggleworx** [soubenz/linkwarden-helm-chart#1]
Hi I'm trying to deploy linkwarden on my home k3s and happened upon your chart.  I mostly like where it's going, but the SSO section of the configmap appears to be indented too far.

I'm using ArgoCD for my deployment, and the result is that I cannot save any values with an SSO section due to the indentation being too far in.

$ helm template test-release linkwarden/ --values soubenz-values.yaml --debug > output.yaml
install.go:222: [debug] Original chart version: ""
install.go:239: [debug] CHART PATH: /home/cipher/Repos/ArgoCD/linkwarden/linkwarden

```
Error: YAML parse error on linkwarden/templates/configmap.yaml: error converting YAML to JSON: yaml: line 65: did not find expected key
helm.go:84: [debug] error converting YAML to JSON: yaml: line 65: did not find expected key
YAML parse error on linkwarden/templates/configmap.yaml
helm.sh/helm/v3/pkg/releaseutil.(*manifestFile).sort
	helm.sh/helm/v3/pkg/releaseutil/manifest_sorter.go:146
helm.sh/helm/v3/pkg/releaseutil.SortManifests
	helm.sh/helm/v3/pkg/releaseutil/manifest_sorter.go:106
helm.sh/helm/v3/pkg/action.(*Configuration).renderResources
	helm.sh/helm/v3/pkg/action/action.go:168
helm.sh/helm/v3/pkg/action.(*Install).RunWithContext
	helm.sh/helm/v3/pkg/action/install.go:312
main.runInstall
	helm.sh/helm/v3/cmd/helm/install.go:314
main.newTemplateCmd.func2
	helm.sh/helm/v3/cmd/helm/template.go:95
github.com/spf13/cobra.(*Command).execute
	github.com/spf13/cobra@v1.8.0/command.go:983
github.com/spf13/cobra.(*Command).ExecuteC
	github.com/spf13/cobra@v1.8.0/command.go:1115
github.com/spf13/cobra.(*Command).Execute
	github.com/spf13/cobra@v1.8.0/command.go:1039
main.main
	helm.sh/helm/v3/cmd/helm/helm.go:83
runtime.main
	runtime/proc.go:271
runtime.goexit
	runtime/asm_amd64.s:1695

```

Here's my values file with some redacted fields

```
ingress:
  enabled: true
  className: "traefik"
  annotations: {}
  hosts:
    - host: [redacted]
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: linkwarden-tls-secret
      hosts:
        - [redacted]
persistence:
  enabled: true
  storageClass: "longhorn"
  accessMode: ReadWriteOnce
  size: "10Gi"
configuration:
  publicDisableRegistration: "true"
  publicCredentialsEnabled: "false"
  disableNewSSOUsers: "false"
  sso:
    enabled: "true"
    authentik:
      enabled: "true"
      clientId: "[redacted]"
      clientSecret: "[redacted]"
      customName: "[redacted]"
      issuer: "[redacted]"
  authentication:
    disableRegistration: false
    PublicCredentialsEnabled: true
    disableNewSSOUsers: true
    authURL: "[redacted]"
    authSecret: "[redacted]"

```
