### ISSUE TITLE
Vertified helm installed in my k3s successfully

### ISSUE THREAD

**Issue by bustersg** [soubenz/linkwarden-helm-chart#5]
Just want to drop by say **BIG** thank you for the helm chart.
I had deployed it successfully into my k3s along with **[Fix default persistance settings]**@Waggleworx 
Plus, to here to share my values.yaml that use cnpg-postgres and letsencrypt-dns.

**1. cnpg-postgres pre-installed in k3s, please pre-create a database for linkwarden**
```
postgres:
  enabled: false # Change because using cnpg postgres
  host: "postgres" # not required
  port: 5432 # not required
  username: "postgres" # not required
  password: "" # Set this to the actual password
  database: "postgres" # not required
  external:
    enabled: true # Change for cnpg postgres
    uri: "postgres://(userName):(passWord)@postgres-cluster-rw.postgresql-prod:5432/(dbName)"
```

**2. letsencrypt-dns challenger with pre-installed cluster-issuer**
```
ingress:
  enabled: true
  ingressClassName: nginx  # Replaces deprecated annotation
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt-dns
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: lw.example.com  # Change this to your desired domain name
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: linkwarden-tls
      hosts:
        - lw.example.com
```

**3. To disable sign up but need to restart pod for changes to take effect.
So, one would false it to create initial account, then helm upgrade true and restart pod to disable new sign up**
`publicDisableRegistration: true # Change`

**4. Configure this link as it takes effect when you click Logout from linkwarden dashboard**
`authURL: "https://lw.example.com/api/v1/auth" # Change`

**5. Didn't had chance to test email but my guess that it should be configured like this**
```
  smtp:
    emailProvider: "providerName"
    emailFrom: "lw@example.com"
    emailServer: "smtps://(userName or emailAddr):(passWord)@(smptRoute):587"
```

**Note: Tried to uncomment for good security practice, but there is write error to .YARN directory or some sort. Therefore, did not use**
```
securityContext:
  {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000
```
